<?php
	//$this->add('pagina/(.+)','pagina/detalle/$1');
	#$this->add('admin','admin');
	#$this->add('(.+)','admin/$1');
	//$this->add('blog/(.+)','blog/index/$1');
	//$this->add('files/get/(.+)','files/view/$1');
	$this->add('gracias','registro/gracias/');
	$this->add('contador','index/contador/');
	$this->add('desarrollos/(.+)','desarrollos/index/$1');
?>